// Auto-generated from global_job_sites_complete_expanded.xlsx
// 196 countries supported by AlmiJob

export type CountryEntry = { iso: string; name: string; slug: string };

export const COUNTRY_LANDING: CountryEntry[] = [
  { iso: "AF", name: "Afghanistan", slug: "afghanistan" },
  { iso: "AL", name: "Albania", slug: "albania" },
  { iso: "DZ", name: "Algeria", slug: "algeria" },
  { iso: "AD", name: "Andorra", slug: "andorra" },
  { iso: "AO", name: "Angola", slug: "angola" },
  { iso: "AG", name: "Antigua and Barbuda", slug: "antigua-and-barbuda" },
  { iso: "AR", name: "Argentina", slug: "argentina" },
  { iso: "AM", name: "Armenia", slug: "armenia" },
  { iso: "AU", name: "Australia", slug: "australia" },
  { iso: "AT", name: "Austria", slug: "austria" },
  { iso: "AZ", name: "Azerbaijan", slug: "azerbaijan" },
  { iso: "BS", name: "Bahamas", slug: "bahamas" },
  { iso: "BH", name: "Bahrain", slug: "bahrain" },
  { iso: "BD", name: "Bangladesh", slug: "bangladesh" },
  { iso: "BB", name: "Barbados", slug: "barbados" },
  { iso: "BY", name: "Belarus", slug: "belarus" },
  { iso: "BE", name: "Belgium", slug: "belgium" },
  { iso: "BZ", name: "Belize", slug: "belize" },
  { iso: "BJ", name: "Benin", slug: "benin" },
  { iso: "BT", name: "Bhutan", slug: "bhutan" },
  { iso: "BO", name: "Bolivia", slug: "bolivia" },
  { iso: "BA", name: "Bosnia and Herzegovina", slug: "bosnia-and-herzegovina" },
  { iso: "BW", name: "Botswana", slug: "botswana" },
  { iso: "BR", name: "Brazil", slug: "brazil" },
  { iso: "BN", name: "Brunei", slug: "brunei" },
  { iso: "BG", name: "Bulgaria", slug: "bulgaria" },
  { iso: "BF", name: "Burkina Faso", slug: "burkina-faso" },
  { iso: "BI", name: "Burundi", slug: "burundi" },
  { iso: "CV", name: "Cabo Verde", slug: "cabo-verde" },
  { iso: "KH", name: "Cambodia", slug: "cambodia" },
  { iso: "CM", name: "Cameroon", slug: "cameroon" },
  { iso: "CA", name: "Canada", slug: "canada" },
  { iso: "CF", name: "Central African Republic", slug: "central-african-republic" },
  { iso: "TD", name: "Chad", slug: "chad" },
  { iso: "CL", name: "Chile", slug: "chile" },
  { iso: "CN", name: "China", slug: "china" },
  { iso: "CO", name: "Colombia", slug: "colombia" },
  { iso: "KM", name: "Comoros", slug: "comoros" },
  { iso: "CR", name: "Costa Rica", slug: "costa-rica" },
  { iso: "CI", name: "Cote d Ivoire", slug: "cote-d-ivoire" },
  { iso: "HR", name: "Croatia", slug: "croatia" },
  { iso: "CU", name: "Cuba", slug: "cuba" },
  { iso: "CY", name: "Cyprus", slug: "cyprus" },
  { iso: "CZ", name: "Czech Republic", slug: "czech-republic" },
  { iso: "CD", name: "Democratic Republic of the Congo", slug: "democratic-republic-of-the-congo" },
  { iso: "DK", name: "Denmark", slug: "denmark" },
  { iso: "DJ", name: "Djibouti", slug: "djibouti" },
  { iso: "DM", name: "Dominica", slug: "dominica" },
  { iso: "DO", name: "Dominican Republic", slug: "dominican-republic" },
  { iso: "EC", name: "Ecuador", slug: "ecuador" },
  { iso: "EG", name: "Egypt", slug: "egypt" },
  { iso: "SV", name: "El Salvador", slug: "el-salvador" },
  { iso: "GQ", name: "Equatorial Guinea", slug: "equatorial-guinea" },
  { iso: "ER", name: "Eritrea", slug: "eritrea" },
  { iso: "EE", name: "Estonia", slug: "estonia" },
  { iso: "SZ", name: "Eswatini", slug: "eswatini" },
  { iso: "ET", name: "Ethiopia", slug: "ethiopia" },
  { iso: "FJ", name: "Fiji", slug: "fiji" },
  { iso: "FI", name: "Finland", slug: "finland" },
  { iso: "FR", name: "France", slug: "france" },
  { iso: "GA", name: "Gabon", slug: "gabon" },
  { iso: "GM", name: "Gambia", slug: "gambia" },
  { iso: "GE", name: "Georgia", slug: "georgia" },
  { iso: "DE", name: "Germany", slug: "germany" },
  { iso: "GH", name: "Ghana", slug: "ghana" },
  { iso: "GR", name: "Greece", slug: "greece" },
  { iso: "GD", name: "Grenada", slug: "grenada" },
  { iso: "GT", name: "Guatemala", slug: "guatemala" },
  { iso: "GN", name: "Guinea", slug: "guinea" },
  { iso: "GW", name: "Guinea-Bissau", slug: "guinea-bissau" },
  { iso: "GY", name: "Guyana", slug: "guyana" },
  { iso: "HT", name: "Haiti", slug: "haiti" },
  { iso: "HN", name: "Honduras", slug: "honduras" },
  { iso: "HU", name: "Hungary", slug: "hungary" },
  { iso: "IS", name: "Iceland", slug: "iceland" },
  { iso: "IN", name: "India", slug: "india" },
  { iso: "ID", name: "Indonesia", slug: "indonesia" },
  { iso: "IR", name: "Iran", slug: "iran" },
  { iso: "IQ", name: "Iraq", slug: "iraq" },
  { iso: "IE", name: "Ireland", slug: "ireland" },
  { iso: "IL", name: "Israel", slug: "israel" },
  { iso: "IT", name: "Italy", slug: "italy" },
  { iso: "JM", name: "Jamaica", slug: "jamaica" },
  { iso: "JP", name: "Japan", slug: "japan" },
  { iso: "JO", name: "Jordan", slug: "jordan" },
  { iso: "KZ", name: "Kazakhstan", slug: "kazakhstan" },
  { iso: "KE", name: "Kenya", slug: "kenya" },
  { iso: "KI", name: "Kiribati", slug: "kiribati" },
  { iso: "XK", name: "Kosovo", slug: "kosovo" },
  { iso: "KW", name: "Kuwait", slug: "kuwait" },
  { iso: "KG", name: "Kyrgyzstan", slug: "kyrgyzstan" },
  { iso: "LA", name: "Laos", slug: "laos" },
  { iso: "LV", name: "Latvia", slug: "latvia" },
  { iso: "LB", name: "Lebanon", slug: "lebanon" },
  { iso: "LS", name: "Lesotho", slug: "lesotho" },
  { iso: "LR", name: "Liberia", slug: "liberia" },
  { iso: "LY", name: "Libya", slug: "libya" },
  { iso: "LI", name: "Liechtenstein", slug: "liechtenstein" },
  { iso: "LT", name: "Lithuania", slug: "lithuania" },
  { iso: "LU", name: "Luxembourg", slug: "luxembourg" },
  { iso: "MG", name: "Madagascar", slug: "madagascar" },
  { iso: "MW", name: "Malawi", slug: "malawi" },
  { iso: "MY", name: "Malaysia", slug: "malaysia" },
  { iso: "MV", name: "Maldives", slug: "maldives" },
  { iso: "ML", name: "Mali", slug: "mali" },
  { iso: "MT", name: "Malta", slug: "malta" },
  { iso: "MH", name: "Marshall Islands", slug: "marshall-islands" },
  { iso: "MR", name: "Mauritania", slug: "mauritania" },
  { iso: "MU", name: "Mauritius", slug: "mauritius" },
  { iso: "MX", name: "Mexico", slug: "mexico" },
  { iso: "FM", name: "Micronesia", slug: "micronesia" },
  { iso: "MD", name: "Moldova", slug: "moldova" },
  { iso: "MC", name: "Monaco", slug: "monaco" },
  { iso: "MN", name: "Mongolia", slug: "mongolia" },
  { iso: "ME", name: "Montenegro", slug: "montenegro" },
  { iso: "MA", name: "Morocco", slug: "morocco" },
  { iso: "MZ", name: "Mozambique", slug: "mozambique" },
  { iso: "MM", name: "Myanmar", slug: "myanmar" },
  { iso: "NA", name: "Namibia", slug: "namibia" },
  { iso: "NR", name: "Nauru", slug: "nauru" },
  { iso: "NP", name: "Nepal", slug: "nepal" },
  { iso: "NL", name: "Netherlands", slug: "netherlands" },
  { iso: "NZ", name: "New Zealand", slug: "new-zealand" },
  { iso: "NI", name: "Nicaragua", slug: "nicaragua" },
  { iso: "NE", name: "Niger", slug: "niger" },
  { iso: "NG", name: "Nigeria", slug: "nigeria" },
  { iso: "KP", name: "North Korea", slug: "north-korea" },
  { iso: "MK", name: "North Macedonia", slug: "north-macedonia" },
  { iso: "NO", name: "Norway", slug: "norway" },
  { iso: "OM", name: "Oman", slug: "oman" },
  { iso: "PK", name: "Pakistan", slug: "pakistan" },
  { iso: "PW", name: "Palau", slug: "palau" },
  { iso: "PS", name: "Palestine", slug: "palestine" },
  { iso: "PA", name: "Panama", slug: "panama" },
  { iso: "PG", name: "Papua New Guinea", slug: "papua-new-guinea" },
  { iso: "PY", name: "Paraguay", slug: "paraguay" },
  { iso: "PE", name: "Peru", slug: "peru" },
  { iso: "PH", name: "Philippines", slug: "philippines" },
  { iso: "PL", name: "Poland", slug: "poland" },
  { iso: "PT", name: "Portugal", slug: "portugal" },
  { iso: "QA", name: "Qatar", slug: "qatar" },
  { iso: "CG", name: "Republic of the Congo", slug: "republic-of-the-congo" },
  { iso: "RO", name: "Romania", slug: "romania" },
  { iso: "RU", name: "Russia", slug: "russia" },
  { iso: "RW", name: "Rwanda", slug: "rwanda" },
  { iso: "KN", name: "Saint Kitts and Nevis", slug: "saint-kitts-and-nevis" },
  { iso: "LC", name: "Saint Lucia", slug: "saint-lucia" },
  { iso: "VC", name: "Saint Vincent and the Grenadines", slug: "saint-vincent-and-the-grenadines" },
  { iso: "WS", name: "Samoa", slug: "samoa" },
  { iso: "SM", name: "San Marino", slug: "san-marino" },
  { iso: "ST", name: "Sao Tome and Principe", slug: "sao-tome-and-principe" },
  { iso: "SA", name: "Saudi Arabia", slug: "saudi-arabia" },
  { iso: "SN", name: "Senegal", slug: "senegal" },
  { iso: "RS", name: "Serbia", slug: "serbia" },
  { iso: "SC", name: "Seychelles", slug: "seychelles" },
  { iso: "SL", name: "Sierra Leone", slug: "sierra-leone" },
  { iso: "SG", name: "Singapore", slug: "singapore" },
  { iso: "SK", name: "Slovakia", slug: "slovakia" },
  { iso: "SI", name: "Slovenia", slug: "slovenia" },
  { iso: "SB", name: "Solomon Islands", slug: "solomon-islands" },
  { iso: "SO", name: "Somalia", slug: "somalia" },
  { iso: "ZA", name: "South Africa", slug: "south-africa" },
  { iso: "KR", name: "South Korea", slug: "south-korea" },
  { iso: "SS", name: "South Sudan", slug: "south-sudan" },
  { iso: "ES", name: "Spain", slug: "spain" },
  { iso: "LK", name: "Sri Lanka", slug: "sri-lanka" },
  { iso: "SD", name: "Sudan", slug: "sudan" },
  { iso: "SR", name: "Suriname", slug: "suriname" },
  { iso: "SE", name: "Sweden", slug: "sweden" },
  { iso: "CH", name: "Switzerland", slug: "switzerland" },
  { iso: "SY", name: "Syria", slug: "syria" },
  { iso: "TJ", name: "Tajikistan", slug: "tajikistan" },
  { iso: "TZ", name: "Tanzania", slug: "tanzania" },
  { iso: "TH", name: "Thailand", slug: "thailand" },
  { iso: "TL", name: "Timor-Leste", slug: "timor-leste" },
  { iso: "TG", name: "Togo", slug: "togo" },
  { iso: "TO", name: "Tonga", slug: "tonga" },
  { iso: "TT", name: "Trinidad and Tobago", slug: "trinidad-and-tobago" },
  { iso: "TN", name: "Tunisia", slug: "tunisia" },
  { iso: "TR", name: "Turkey", slug: "turkey" },
  { iso: "TM", name: "Turkmenistan", slug: "turkmenistan" },
  { iso: "TV", name: "Tuvalu", slug: "tuvalu" },
  { iso: "UG", name: "Uganda", slug: "uganda" },
  { iso: "UA", name: "Ukraine", slug: "ukraine" },
  { iso: "AE", name: "United Arab Emirates", slug: "united-arab-emirates" },
  { iso: "GB", name: "United Kingdom", slug: "united-kingdom" },
  { iso: "US", name: "United States", slug: "united-states" },
  { iso: "UY", name: "Uruguay", slug: "uruguay" },
  { iso: "UZ", name: "Uzbekistan", slug: "uzbekistan" },
  { iso: "VU", name: "Vanuatu", slug: "vanuatu" },
  { iso: "VA", name: "Vatican City", slug: "vatican-city" },
  { iso: "VE", name: "Venezuela", slug: "venezuela" },
  { iso: "VN", name: "Vietnam", slug: "vietnam" },
  { iso: "YE", name: "Yemen", slug: "yemen" },
  { iso: "ZM", name: "Zambia", slug: "zambia" },
  { iso: "ZW", name: "Zimbabwe", slug: "zimbabwe" },
];

export const SLUG_TO_COUNTRY: Record<string, CountryEntry> = Object.fromEntries(
  COUNTRY_LANDING.map(c => [c.slug, c])
);